// release 0.87
var vrm_character_array=[],character_load_flg=-1;function read_vrm_file_api(a,b){var c=new FileReader;c.addEventListener("load",function(){var d=vrm_character_array[a];"undefined"!==typeof d&&scene.remove(d.scene);d=c.result;character_load_flg=-1;vrm_model_load(a,d,0,3,0);vrm_anime_check_change(character_change_sub,a)},!0);c.readAsDataURL(b)}function read_bvh_file_api(a,b){var c=new FileReader;c.addEventListener("load",function(){execute_bvh(a,c.result)},!0);c.readAsText(b,"UTF-8")}
function execute_bvh(a,b){var c=(new THREE.BVHLoader).parse(b),d=c.clip.tracks[1].values.length/4;pose_content=vrm_character_array[a].humanoid.getPose();Object.keys(pose_content).forEach(function(f){delete pose_content[f].position});for(var g=0,e=0;e<d;e++)setTimeout(body_pose_set,20*e,c,g,pose_content,a),g+=4}
function body_pose_set(a,b,c,d){input_rotation(c.upperChest.rotation,3,a,b);input_rotation(c.chest.rotation,5,a,b);input_rotation(c.neck.rotation,7,a,b);input_rotation(c.head.rotation,9,a,b);input_rotation(c.leftUpperArm.rotation,13,a,b);input_rotation(c.leftLowerArm.rotation,15,a,b);input_rotation(c.leftHand.rotation,17,a,b);input_rotation(c.rightUpperArm.rotation,21,a,b);input_rotation(c.rightLowerArm.rotation,23,a,b);input_rotation(c.rightHand.rotation,25,a,b);input_rotation(c.leftUpperLeg.rotation,
27,a,b);input_rotation(c.leftLowerLeg.rotation,29,a,b);input_rotation(c.rightUpperLeg.rotation,33,a,b);input_rotation(c.rightLowerLeg.rotation,35,a,b);vrm_character_array[d].humanoid.setPose(c);renderer.render(scene,camera)}function input_rotation(a,b,c,d){a[0]=-c.clip.tracks[b].values[d+0];a[1]=c.clip.tracks[b].values[d+1];a[2]=-c.clip.tracks[b].values[d+2];a[3]=c.clip.tracks[b].values[d+3]}
function vrm_model_load(a,b,c,d,g){my_loader=new THREE.GLTFLoader;my_loader.crossOrigin="anonymous";my_loader.load(b,function(e){THREE.VRMUtils.removeUnnecessaryJoints(e.scene);THREE.VRM.from(e).then(function(f){character_load_flg=0;scene.add(f.scene);f.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.Hips).position.set(c,d,g);initCharacter(f);vrm_character_array[a]=f})},function(e){e=e.loaded/e.total*100;console.log("Loading model..."+b+","+e+"%");display_user_message("Loading model ["+a+"] ..."+
e+"%",a,!0)},function(e){return console.error(e)})}function vrm_rot_Head(a,b,c,d){body_rotation(THREE.VRMSchema.HumanoidBoneName.Head,a,b,c,d)}function body_rotation(a,b,c,d,g){b=vrm_character_array[b];b.humanoid.getBoneNode(a).rotation.x=c;b.humanoid.getBoneNode(a).rotation.y=d;b.humanoid.getBoneNode(a).rotation.z=g;renderer.render(scene,camera)}
function initCharacter(a){a.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.LeftUpperArm).rotation.z=Math.PI/180*72;a.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.RightUpperArm).rotation.z=-Math.PI/180*72;a.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.LeftLowerArm).rotation.z=Math.PI/180*15;a.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.RightLowerArm).rotation.z=-Math.PI/180*15;renderer.render(scene,camera)}
function vrm_rot_Hips(a,b,c,d){body_rotation(THREE.VRMSchema.HumanoidBoneName.Hips,a,b,c,d)}function vrm_anime_check_change(a,b){-1==character_load_flg?setTimeout(vrm_anime_check_change,700,a,b):(display_user_message(".completed.Drawing",b,!1),a(b))}
function character_change_sub(a){var b=vrm_character_array[a];vrm_rot_Hips(a,characters_rotation[a][0],characters_rotation[a][1],characters_rotation[a][2]);b.humanoid.getBoneNode(THREE.VRMSchema.HumanoidBoneName.Hips).position.set(characters_position[a][0],characters_position[a][1],characters_position[a][2]);renderer.render(scene,camera)}
function display_user_message(a,b,c){var d="";1==c&&(d=document.getElementById("user_message"+b).innerHTML);document.getElementById("user_message"+b).innerHTML=d+a};

